name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '1 3 * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://feed.cnblogs.com/blog/u/564456/rss/"
